apiVersion: v1
kind: Secret
metadata:
    name: smb-secret
    namespace: kube-system
stringData:
    username: ENC[AES256_GCM,data:U8SRfwRmU+6FdLWMi7eizxCNH2WC,iv:OTPL5p3vyvkaTSJTY0mXdrRZNRYTgqMU59KxB9saqTw=,tag:SHSbjh03TFU7sVeS6Tq6OQ==,type:str]
    password: ENC[AES256_GCM,data:Ce6+W1tAQ7ky,iv:kH7BeYOlnLfBoqLPzjEEFs7lkdzlY54bhZ09IATOAac=,tag:GGWWXPMUA/M9TEBMmi9JFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMnMxNUhDU09OeXJOYk9D
            Tzh3bjg4S2tVRGJnRVR1VXVBSldJdUdJZ25BCk5iRzJ6QVVLbm9LQmhZV1ZiTkUx
            cnpRVllXbXRnb2hENzhBUzFsdU12cEUKLS0tIFExSXRvUHZVamN3aWcvbHVvVDQz
            Z3VnaHRyVkdLZmJnWDFuc3FLMHlLdUkKnbkaNXe4TEHR+Q8A1jSP19NMCzPpCRmo
            Xt36z7j4ya4q0xbRG9ORnWEXfysZzhHUBKgmt6dSKZQ0ZUG/exiFTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-14T23:58:35Z"
    mac: ENC[AES256_GCM,data:JydQr9s+h/m9FuNiioMUmzY6WBOzo2AZvFU3fQ1MQp+Ooa8dHmOYhfmJdXHHFaP6PZeU+7/SN4tzN/u2mrZjgDphgwRPrkHzXd/+3maDVZ3x3c1V66HuW6AGVTLW579v8yN9mLyGaNih7Ouobp3bT4vlOZF3fXNcWoeeZkUzN1M=,iv:gM1zv+JsJ02ZcllIpNLKXkUssL4nh4svKYIBTqfYoqw=,tag:+iTC5qOLmIQ/fZK55w4X3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
