---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg"
