---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-csi-1
  namespace: system
spec:
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: nfs-provision
  resources:
    requests:
      storage: 500Gi
