---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-csi-nfs-7
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-provision
