---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-csi-smb-5
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb
  resources:
    requests:
      storage: 50Gi
