---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-csi-nfs-6
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-provision
  resources:
    requests:
      storage: 50Gi
