apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
stringData:
    root-user: ENC[AES256_GCM,data:asK3OgWiZ3ZnoeO7BQ==,iv:d4NatevvQzlZjXyCyvgUq23N+BfwUtqy+tAFLkOQcq8=,tag:va2qX1F5+k7XveShVtCPeg==,type:str]
    root-password: ENC[AES256_GCM,data:Q+Q+l0S1VZGIbd4zcxyvV5kMpUob5UdIsdMtPHwB2DVpPq+Lgw==,iv:EymIXsj4OSVdFJzFEtWNBgLFrUdsbPmG9NVPLUw11jw=,tag:6zPgSKuS+1nRZUHlswE5Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVjBYVDUwV0krUUkyWFJE
            TjZpcnJiSHByV1lLUW8wQ2g2emlHcXdDRWlnCkNiL2dKVzB6MTE2SkkxdGVRaFds
            THhRUGVrVUZhUVVTWHhIeG9xcXhKbzQKLS0tIE4rbUY0dU9xaElJNDd6cVduYkZl
            dWxlWkVydGZjamRlT0MyM3R5WGR1QkUK9GycWmXk0dZ4nRDxB3Ipb0h7/imdk9QM
            Xb24qU1pkb17T+DQXLVmTfuM5xqmsTW9rRFlqwVchoIg8cOWZ1guKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T23:02:51Z"
    mac: ENC[AES256_GCM,data:81EWmlJJiC7huyHA9ME7V/y8GJoyZPjBP+mZKwlW0TyNfWGeofpXQdIStfaPeL0gdLP6+Kq3UtB9iWA81eiXliiNZ5Ak6DMwxWJg07jZSrjkgntP035DQ+PdXa1n8MPtjGU6J5nO7zILXZ+p2RdCRXp6Lt0ecYF9VtPIojxWneg=,iv:QgeldMKyrcwoV3NkL2diVSjb8t3EXiGlLnQ/S0TNfHw=,tag:OPMZSIeMdD1FckQcz2Merw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
