apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
stringData:
    root-user: ENC[AES256_GCM,data:54qd3tQaVxX9jWfp,iv:9dTlP/BazGLUZlmx9+vHihHr3fXnSvaQgwZAYJkJwTQ=,tag:vXCicUhXtsxVLvXocCvXcA==,type:str]
    root-password: ENC[AES256_GCM,data:Q+Q+l0S1VZGIbd4zcxyvV5kMpUob5UdIsdMtPHwB2DVpPq+Lgw==,iv:EymIXsj4OSVdFJzFEtWNBgLFrUdsbPmG9NVPLUw11jw=,tag:6zPgSKuS+1nRZUHlswE5Yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVjBYVDUwV0krUUkyWFJE
            TjZpcnJiSHByV1lLUW8wQ2g2emlHcXdDRWlnCkNiL2dKVzB6MTE2SkkxdGVRaFds
            THhRUGVrVUZhUVVTWHhIeG9xcXhKbzQKLS0tIE4rbUY0dU9xaElJNDd6cVduYkZl
            dWxlWkVydGZjamRlT0MyM3R5WGR1QkUK9GycWmXk0dZ4nRDxB3Ipb0h7/imdk9QM
            Xb24qU1pkb17T+DQXLVmTfuM5xqmsTW9rRFlqwVchoIg8cOWZ1guKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T23:02:22Z"
    mac: ENC[AES256_GCM,data:18wdQJmGYfeUsAPH+Vi9qk+YwopefwpVqEdqLpse4U1CohZG9Gg91cvl9hY9FyZihyuWX+MgBgmd1ZDFSyIJQa9YkNkGBYQYOOefWky9wNPSIjnCbMQKTdDRnqxXwpR6nD+fsredzaUfUJuj89UlQpdh1VIEbNe8bXVf4Zp+BSY=,iv:9dcIGk5bM7bylkQuN/tUQ0NiQpRXXnxTTaOv2tqxhgM=,tag:IY9Mq858BFjDCcGyy55eLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
