# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app netdata
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: netdata
      version: 3.7.88
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system

  maxHistory: 3

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    controllers:
      netdata:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            env:
              TZ: "${TIMEZONE}"
            image:
              repository: netdata/netdata
              tag: "v1.45.3"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - host: &host "netdata.${SECRET_DOMAIN}"
      paths:
        - path: /
          pathType: Prefix
          backend:
          service:
            name: app
            port:
              name: http

      tls:
        - hosts:
            - *host
    persistence:
      config:
        existingClaim: netdata
