apiVersion: v1
kind: Secret
metadata:
    name: vault-secrets
    namespace: external-secrets
type: Opaque
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:8i0D8XRRgNsL4pGX2cqyZk73r6gGE62Sfr+Fjsi8U7hcnNw/Ol135T7c/PnC7Fl4PQ==,iv:8es22edKkzMav3hCI6Uud9McqINSun1oi5096a6J7yY=,tag:maYKchJBbaLlExtlB+s1ug==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:7KGbaeRpxI3TM5xoJHCtnwRTxg4ZcYoui9ylseHb,iv:GLM0oRJg9gsC1r+DSpTVjFhFXYJozyO8rewWYl9np7k=,tag:X5fJytBI4v/SkAWLxPuYSw==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:qo5yIFad/3/ktx9pHKC2TlY3vFs=,iv:7UHhXtQrm/R+Diz8dryrWhIco4Z7+H6YBsupIDtjdKQ=,tag:a7KUAJtZiE8oi4DTndl4JQ==,type:str]
    BW_HOST: ENC[AES256_GCM,data:QAD43IojJF/hlSQjqBlCjL7lgBHE++UbIqvt,iv:2j7pBH2gup+5jkRhQVzNgLtusH+vKiYvQdvCpZ4hJeY=,tag:CkzypFbym7ZU4K2ecX+HEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCazFYMm93Wm5XbmJnTVR3
            dHVIY1NBMUZyUWV5RFhGd1lXelJWdDB0RjNrCm9jalZrMnIzazU2ZDNyU0RjUEdU
            Q05Zc3pjcTZSTjZSZ2plU0QxT21hYmMKLS0tIEVKVFFJMmFZR05ISm5pbXlhK3k5
            OW9KY0U1UEJia2Y2cUJQRjRhODFvVU0Ka5Qx1hytl0Q5QZGTomjT9srAOiQGDJzI
            7Wd2sfAS04B1DCullV8heQ+IyyCZukc2yHs+3VJi3R3PhjbxdjRXzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T21:29:16Z"
    mac: ENC[AES256_GCM,data:6MC95sc3eJfrpHqQWRqpXpiFGUUToVsUT2YYRsCDAbzztPsY54YsUhPpPDlHO/rkB0ZWQgIeb4QJqaUFCNW20rtpPIaz80vRK5V7xk3Go3/Ckbkpj+npR0I32yRXfe/GzinZTfbIiXJsPHvXaB8T+9pujN8c/eu84wWSDhxZ8TM=,iv:AiZdrJXzR1Wx16L3Sl1BMla0wcCP105waAtqPU4MDtI=,tag:Cu11tmzX3ElSUxB3J3az8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
