---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./stakater.yaml
  - ./external-secrets.yaml
  - ./csi-driver-nfs.yaml
  - ./csi-driver-smb.yaml
  - ./nfs-subdir-external-provisioner.yaml
  - ./mojo2600.yaml
  - ./longhorn.yaml
  - ./weave-gitops.yaml
