apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:xSpRintYxO8yfv2t1ED/9cG7fwK9MyCLyPp5+qybpwQQh+NO,iv:udP2Y3CblG5l49tKYAZKEoGkxZAGTyjOTxRXf2R0NLE=,tag:VcMDuAedpfaLcW7CG0BVfw==,type:str]
    credentials.json: ENC[AES256_GCM,data:ur9y7UQh0/ASF5uNjJINYzDUmINLY8+A+vyfgJtiYzLgiTioY7Zxuy9ZqFyz9yrT++REuDFPFg/Ty2F3ECAUFDujGxzWh1lIRfPyKY2qqd3rE760Fa1Jd6jA8zdzn6dfCn+NACqIE1UAhaSFwPUzETk6nJvsICsgDeJ0tbmAXmFLIJc60Q9luNn/LT6vqS0umQngThOQbXOjJk3KwqDcCBXN5sy9QHpf0oq/yIEifw==,iv:pbtMGeeoJ8Lv3wQBZwKZlo58SpBGl7x6i3Z8G2UIsVE=,tag:XCYRDUU/T0pZCHanpiJkdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ah9ykhxj8jzudx6mu40wazdv9nd3n5zhd86908k5q6l5g53sg5asvwcms5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcktNNkZPN2FEOVgyUGUv
            TFNhVmdVYkVQRnNuNC9uYWFsMTlqKzF3bWtvCjVLNThBUGF4UmpLKzNvakpkWng5
            Z0VwemxITytCTkF4bThkRUs2SWVLejQKLS0tIEJpcmptZGJtbFhrdDNvVXg2eFdR
            QzJIaGJwcVRXS05nQ25oWjk2TlpsY0UKFRLGCdQbyLWK+UNY7+Wrfp+8RQ7SfnmT
            4+nrF3E8ePemdtOcUDrWQbV0zOHowxgvzcNnYJ/01TegAwZKgzr+sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T18:13:28Z"
    mac: ENC[AES256_GCM,data:qMf7eL1Rm85muiPQQtXFM1yWTryzJmnPIkvh3JS2VbYo5Eh9xebwc6QWdkBo1FhlIUIgm1adtC4xC0q3mwt36Nk3ikLhb8zdYzoUNuRcPGd1HmrMHAQrwy4eY0Y63+f0+SNjaLOUQuzgfzaebdKV2lIDYFE0jHPRu6/vExE2jlg=,iv:pTMv2IP/TSZc8Fb0XekVSGDweYHkr+jWLjM/ZS59Pgo=,tag:/Ll8GXQ/ImXj1M6RRGlZmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
