apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:KG107jARHzxwltBmek0MP7UyB9omA/rL5hOhhPgwDXX7y29c,iv:1TcvdfyuY05U0R98IkaGBtDqQdA2j3lfI4nUSnPW4Qg=,tag:8Fh5nUe/kI9BS+HbUk7Hcw==,type:str]
    credentials.json: ENC[AES256_GCM,data:JiQVkEnVUqCIyNCxrAuXXDfGmcyaQGXjinx01zH1YvbeYxgGfWsMtoHWnByIskJmZvNJ8V9oLrspzWk86s+LNTZTHa18s62mD52AmF8LS0o3u9VQeqWI6oxqUT2ajjt0DHzzLtv34CJTi8jymaa06AcCO/xvnx4YGRVoxe5594DuduXN9MIUdsjpl+ter2r9q3dbIiqDQS1yr8BWibM24v0RqfA8v10mNgCDo1kgHw==,iv:Sf/PF/UV1CejBjDwmKGp1su9a5KX1sFY1/eSQaUQgn8=,tag:eKnH5gr56EeeEiBUBUEqbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ah9ykhxj8jzudx6mu40wazdv9nd3n5zhd86908k5q6l5g53sg5asvwcms5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TGxKZGcrejE4Z1g1ZnhX
            QlBpaGx4bkZ2dXZvbmc0TVZLYlZrakJKWUdnCks2UlIzRUJlWlZlRVdyVHV3dVlC
            akNJOEJpa0hXSFpwRlUzOWM2UW9tc3MKLS0tIE1nL1hhMUluV2NEOWJ6bzZGNllm
            YTRlSUlWTmhmSEVrRWczdDJZVTdDUm8KKjJ1QWw8U9R5ZOKGTh855jva7Wq42e3L
            0TPb4vlmbu+Od00Os+rjcK4WAMJ69NWYR/+7vUz33/XaJlcyRP2+Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T18:09:35Z"
    mac: ENC[AES256_GCM,data:Xlbo5LaLTxyiPFUNYhKkaMF12N6H5SAsEJmot3vUFWOMszJAcFQb9QZTH0VgL5wjMkKt1fwZWghxkg5EII61dmyo1VI3xsScCrIWhze7bjgXowfgaROI2yVce/ti0/lsYfxbh29+iw6ewNCKP4b0k6VXuLnXPS5Nd+fnd0WYm1o=,iv:L0iRwjWPQqbKLuFjI1Mbycu7aZDN2ouLOGbTvy6F/to=,tag:c3+9sp/hA4u9+p/hdK1t6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
