---
kubernetes:
  children:
    controllers:
      hosts:
        "dev-k3s-01":
          ansible_user: ""
          ansible_host: "10.10.12.111"
        "dev-k3s-02":
          ansible_user: ""
          ansible_host: "10.10.12.112"
        "dev-k3s-03":
          ansible_user: ""
          ansible_host: "10.10.12.113"
