---
kubernetes:
  children:
    controllers:
      hosts:
        "prod-k3s-01":
          ansible_user: ""
          ansible_host: "10.10.11.111"
        "prod-k3s-02":
          ansible_user: ""
          ansible_host: "10.10.11.112"
        "prod-k3s-03":
          ansible_user: ""
          ansible_host: "10.10.11.113"
