apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:5BesWUdSZrPvXUzyd30DHLqT7hkyQeic9n1Sd4jSi+SrZ9500/hHFg==,iv:We+cRM4/TPowf6SOvLYhCAWDuBp6rq1mV+j377h4/XE=,tag:zvbBDQyMBdFK10/OK/JlrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTExBcnlyWWJPTWF5RnNo
            eTJjYS9mS2VLRElHMXRZN2d2UG8zNGcydUg4CnJ4LytUSmZVMEx1bnlzUDRvYzR3
            VEp5RUwwbXY4a0M3cU43WDBHOWJoWm8KLS0tIEJ5QUw5WkExQm9nVGFkQkE4bmxz
            WFFST2syWmxKMndIbndqTXkrWEl4ZXMKFT9nZjhBk79LOP8juzDxyWwKZ6aVQ6eo
            EfJmdTQOJRwU5i0CApdZcclykgi0nES1Cq7qmgdfkGotMdx1guL1lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-18T23:33:02Z"
    mac: ENC[AES256_GCM,data:0g6iPakqdpdBYnP2eq1POgtzBStTJgzuCaWTQCVwXvQN3xiX3TGjqPqD1TrxikhbZo8iMdg6ALsOj8zPeQOWwICv+mS7Kb23wmju9F0frTgdTjt1DO+yBN31GnUdM9vAFANzvlQtemjbEYMXgKfbo1c/iEh6EeEOiPWDRwC25YY=,iv:fu4X8YkjEj0NT3FopNkyUriC3cteQNBpkjY9RN1Msbk=,tag:WitIaQdNG6Rney3HilRFaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
