apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:l2Qx6B5D4DcpSXH2hhY/K0R4nqUZ91YHQ0GuAfF988nrH6EMeM0bcg==,iv:kzrh//SFnLr4m0AaQc0nDrJSjp14WHuF23IslrM6+a8=,tag:+mLvsOk0F78oKkz27YZGGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ah9ykhxj8jzudx6mu40wazdv9nd3n5zhd86908k5q6l5g53sg5asvwcms5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaU1ydWkxUFBMdG1rV2pu
            RkVxRmd4TUx3eGxJSks2a1pMSDFRTklFbTJnCmZRMFI4MXowL1lERXB6UE1QZnlB
            ejY2bzNOQ01Wc2o5SXQ3OVVORGxwdE0KLS0tIGsyUUh5VkE0RlRqcHVhSlRlMnQ1
            cnZhZHZNU09CK0xBUzlsMlBmMkkrM0EKQVz+PmJmPTR4H1yoyRgs8EyuSp3sDt2C
            go22Sqi2JxyloQR2HQrp/GcqcLeEUWmkacTKmogf0Rd3bVAIVRliCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T18:09:35Z"
    mac: ENC[AES256_GCM,data:FT8Ju97BzMlq8OTcUeNp/lX+TfFbosf7wlDhbArHTWqx6fSX7m3XNw9FjC6QPqouYpYKpkY6IjkjTzYZ9VH9Y9EurSL8s9mvcL5IK8dJL6KnPYNe5ZQkl5JLgo6rWfq3E2XGhM0HCkAMLZufEYemuUXeFJ/jPNeToiOYPkMBY48=,iv:D4m4alK4WUmOssygGEWBSSgfYbZ6tc1ruiAKx5PPUt8=,tag:2oSNWlOGSAqOLxcSZiqbtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
