apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:/9Zywsj9UyK8f3HmH7ScMca4d7DFzgyN93m48aqKvZeevGo2oWOSfNT+uzJPQNBZv7gtFI65OwQVHMyMIt4IGapaXwmqm8tqiPpHEbFVb8VMujEtJW2Cz0wsctDRpA==,iv:bmh+jf3SElxSDW9TjoLSyhKsWyH6GlQsVNdBpTOhh9w=,tag:U2Ts0vnEE6RME8TEp94jZw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:zSQE36D5mGQw,iv:760eR1lMUFnTnNAnSXjmyl9dSDVsYNOvTqT7gQIdRM8=,tag:HIwsHeY5c7hRUPQ6pFdQ2Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:i1F0sKn+9oaE8ftLDnlI,iv:YTsvE627U0My8zaawONmTmRnzo1Sahuu0tyBHEW9rcY=,tag:3O0XuLnPaR8pUKesoNn/eA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:h1WyncyXLr/Qrb+vjcBugsiFw8IE5f6vhh8AtmT0zBOukRcP,iv:cVZQrO8me09qIb2IHb5lcBToiuiXzfIQ61npCqmZOQM=,tag:jy/uwQmNm/7Wi1H+dsxqCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ah9ykhxj8jzudx6mu40wazdv9nd3n5zhd86908k5q6l5g53sg5asvwcms5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcFBtUkZXRTVJWGlmNnRa
            UWRvWkg0TzJqTFpmSXVFWkN2dXFBTDhiQ0hvCjlVcmpnRzd2WE5XVmloRlUyRHMz
            dlFkM3pPV1hFQ2hBbmR5UlpUK1ZJd0UKLS0tIE1FWmtoN0dQTGh1d050Ly9UVmkz
            aW1aYWtqSEJFNmZ4UmVCWlJGSDhYRTgKb2sP9W+iaDSPOKPqBybXdzhLR38J5Z6U
            L7x4kTB+nB/jpDzs1/X8h5+PiGCo6SWB7rz/LFeLJbpdPlgiRcTghA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T22:42:16Z"
    mac: ENC[AES256_GCM,data:I3yS8dCVlBGp4hmK/QJRtrIBmVEDy7zzLqYi2gCTSn6cuR8UCbUmeUgU0S4jteMbOKx6W4RTfaILLgjwQHDFBbp0L075fpGoxleThMHtK+cIY7QfzTv6XYxFMlCiH6DEPFjN01tHnMN6KFiOZVM56veqUZJOxD8NfJHLz6Ci7V0=,iv:/qlXTNztPfey9GDCaf4eGOVUU+hMA79lviKiBTIeL68=,tag:Gi9ngexWqd5LC11fcuWSMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
