apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:YvdA5P4iuHpgUrDY0revpSCgfYWu15wPi0Dau3gJCpphAGNBNOtWmb/+9fyEE6lrsCJsTcvsz6kN6Btk9G7xJDtMfTSz4I908swJlOoGq9xOIA9ulgH7iZPco8NVNw==,iv:HUrMq3AoPqsYzQtulz/7D1ctEANQe9r448KPNNkHmyI=,tag:b9z2D2oJzKIxk6ZjExOfiA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:P5rNUTEEXhWM,iv:ctf+b1ri0cHtco+02bG8cnSqeApU8N2j14l8HgdH1yA=,tag:VllwpINimPTwfmZGx4r6og==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:gCnZyelJqk2aGroEYKh0,iv:ugBPWrrrkAxMPceRCVIBbdb82U+7COJmJ8KbNuBAZpA=,tag:dYjqQyVgVZ5k7jsBwOHpqg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:nH8vm7AeCZKMPBcobVRY4AeJjdjrjA16ISi2cZyhaEDUZNwP,iv:vb+UkEm6TX/mKHPXZ/f3UVRRza8ckCfdU4xMbDZuJNk=,tag:l4po4OqgNwxWPEq5bAkEZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MlVvbFJ2cUpHMnF6VW1L
            NUo4Qjl0VmNKQXRmaE1tdVpRR2xxZVFwalZJCk42TW5KOEJwQzlMS25McWxQeGtK
            bDJBT3hzTGZvVWtMb1E1RVdhVm9LTk0KLS0tIDhEM1FwVUdENmdvUGRDdmJzRFdY
            Q1IvSWdDcDFlK0s4amxKeXpsUUxLNkkK9eH7i+yEzgUdsgH7TgXNPcGuMVZlLlhB
            bd9XBxmJSTlHNa8n/8abujmBvkmUHgCe0GeQch4Aa7zkJZlZDJCvcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T19:00:59Z"
    mac: ENC[AES256_GCM,data:/y1Ca37jQXWfBXaom/H8+9XAF1CumQ8muVOy3lqfKtN+Xj6te2BDJ83iuPZzmkc7DQXg3O4shlzISwdTYBugKaXOMl0NQUVMUmV42F6ngnuuc5uBwrA8IqVPKMLfrNSf3s+lGoVl1Kkd+Phqa+ykjIiFXfuwByiT9MirSyQ47pw=,iv:foze1KczX8chCKDvT+69EFsTA4VoHOg7FnlyM1F3amo=,tag:uwzL7+mwO327Jalou602nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
