apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:94sk4C3+UXisLqPyCPU+GGU6+2UCJP1QumMEzL5ZU8ZTuWoIGupd+A==,iv:FdHBodx8V1gmwGonu7M51IALlMycvOkudqhtGTnWC5M=,tag:BOKJvh18o8eih2E5sCItzQ==,type:str]
    username: ENC[AES256_GCM,data:70hZK7U=,iv:8t73J/wfba85J9P/jqb0pneueXX6FrDcF8Uqr1iPH6g=,tag:o/SYLIGGraTdVIlMPIucJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeXlnd0RlblJESVdpcmFI
            VlhpdGNCd2VFbEdsUEw1NkZSNGVlT1VJMmo0CnVpVzY0T0lxWmI4eUZPeDRVVVND
            RldEYWhtUytXekNtdTZ6WGdKQUQ4WGMKLS0tIHZUUU9hVDRWRi94cUpYOEQ1UnY1
            RVVsRlRlazBKU1ZOeGpzcFBtaHVDWUEKMF1Xd/1h3+Syj9v4OpWTwSsXaRQLT/Lc
            xABTWr0mGzNllBhptTOII26gXjTsCtiLBYrE7TtdQ1FFKFPgxT9K7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T22:16:47Z"
    mac: ENC[AES256_GCM,data:EFmdivUqehCoam+03ecPd7+rWmAZCpqtuaHuBeYAwwxYHjDtOXo8b6z+yZyUBNrIvNFhuSMKUYyMFGvw9LvAyUGwfCEYV5gcSu9DisAqIhIqHFi615d78nu6ttqyDgAbczQqLJEef5wkts97hSQj1aBaLz+Jq3BLFBQ7R2xLHp0=,iv:W3Qk0my4hYySvZ5i8tEQNIzvkDuNjHgE5vJY3/vRjVw=,tag:czJ/lMiI1mIgqeGB4eJvpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
