apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:XCjvgFiO5K2Cz3kg9wjZx1MG0vsaYG7efjhQjPx1KeM=,iv:+KbOY5OvmAFCBcqb6uf05+oMlMZlK1nBUEj31js9d7U=,tag:iUHJrJ8r9eJr8zkCadUI/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbXZPekNnOUtRcTEwbDgw
            cXRCN1ZGb0tPYVFqU2I5OWoreFc4dzRONHpJCkR2bUNwV0ZBcWVMRDNoNmQyemdq
            ZVFmWGR3NVk2S1RVL0R6VEx1Q1lYeHMKLS0tIHlHd0UwNjZCVWpiakx2ZDM0YkVr
            cTRyMU1yREwxZEtTS3haeHhKclBxbkkKFHbddx6HMYrt+c7cC0zt7bfnElqjt1I6
            wuWl4OYS8yh4TVnuzXSKx7ZQkCoWLH0BwoqKpcWy8hOWG2ojZ4eB+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-18T23:33:02Z"
    mac: ENC[AES256_GCM,data:frMDXDeKb9GK+jbBbd76FiPf+G1dn25YlAkGXvBqN0koAJzRr/zZ/HGeGaWjYsu6wp+iogzOIfImrzn/Ad1V2pINVKyFsNteWVqf5bhBt+oWirM99nO2K31tWcfmF7bZm8lRT8xV/m3RkUtocnegoH8aOzCcT+zqd/dEWbUY4rs=,iv:givaR9ZgcdYSTS/AlKWiSab2sbtzbycwGNNWqRef7sU=,tag:kWb+Lptm+FCERca9Jr0Pew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
