apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yYAA+9iG+emt6sYUYojorFqYfPomAUc0k8WvELyAlKIAiwKNdmmaTQ==,iv:UKDyT1z0uHM9J23A7abwzYrQeE5pMb6OVweJmSPFwMM=,tag:wY3yvEdx5krIFIU0Ac1ibQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUzRWWlVNQU0yWEtFcXBP
            VlFVRUZnNkMwZTBjbnc3RitMeC9iSGpZMkFzCmNLZmh4cmMzQ0EyYVozL0l5cUF6
            YkE2WjNRbkN0aC9Xc3E2OURWbzFpcGsKLS0tIFhaK1FvVlRlZGM5U2trckVrYXZv
            aEsvdXl3MWhLZm9WTVE2TVRKTElrNlEKi4Y5hJ8p9fZdGzctKWstMET/W+BKUz0d
            tIuZm2WhdsMQsZkfYtSqEYBez2yR8dNliHG/ZV7Wo+hzWI1i6leKJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-18T23:34:00Z"
    mac: ENC[AES256_GCM,data:LDeH18rZKw0NMjCI4vak3FkHs5gsaEQ8dFsA2Ch3V1rqyEPxh5CUXNLogG886pjdoKw+SLjfX+osU47Zuq4m6Z6r3vwdX7FvLmpd/e1otttRagyfZ82vKaVif6s9EX/D7lM0IXaaCtXt+wec+WBmYxQaDFKdp3CC0N/ibdvd7ik=,iv:GeSpUC/BRzvzoOm3MCzOssf4nR9EwEn408Khc8Q5TBI=,tag:kzkQGb2puP/E4dBkpqC/Ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
