apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:qfjPEtg8wo2Lm/lWskBYn//pyWjib+J33Asefckm5gN3y4U6/n01qg==,iv:teq5/fdQ2mffEOYJoVPdcjPZp92d2y3Y3g898X+Y4E0=,tag:vltCXupwts45nLRfYdIfEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ah9ykhxj8jzudx6mu40wazdv9nd3n5zhd86908k5q6l5g53sg5asvwcms5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodWNMSG5aMzRwYzdBcmNF
            d3FyK1VIWWY4QldIZEJXbUd1Q3dyQXpPVXdrClJ2TXlHNFQ4eTNSTXNOUXJHN1Vy
            Zk5naUNybnlHcXNRQU5STDVPaEtUK3cKLS0tIHFraEI3YXcvU1R2ZnVDUG1MRFBs
            ZG5EeUExZE5yVEd3Z285a2t3WWgrd2MK7wPn7jhtpxYZ3Ts1/TYsNRgGf9dn2Cv2
            Tx0ikZNJxPz37YfcWyBzFQvDFXs+tU7dSFqddfJ0HQ04vvdj1a9Nug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T18:13:28Z"
    mac: ENC[AES256_GCM,data:z92/f7UWIMJr3RlG4rXGFtMYiTjtA07jkZ6pG70JW7zZKkr3FDdJY1BtT3AD4mmKC9eSVC6+fDuKcE7+7ZztQHOPBDVnGWQPy6oniOwUjo2j8BZz0prJnYiO/4+WOFXeCTOXoycurzq8v9hm03wu5/Ucd1s9q2QWDiDt+JsbTT8=,iv:TM0YOs+MKKpQRk3ljTUZRyNztiXfagIEx7tP1xW/liw=,tag:LrQbm+vchTm9N+9NLDLHeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
