apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:bjRKQgEcnpl2OB0Ak5E9j9ni/5ZE3Q2zLyhSV27poxZ12/UW2AJ8KA==,iv:QEN+xcHK4pAJs5FIrQCvhr7vBiS767TZ15oEBYue5RM=,tag:7yKR6kbj36qpYJD1N5JuuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12wqtjgeefj5zrx2jt9mj6lgnunhf50swqc44ldeas43scjph4feqw9y8mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcGc5S2xKYzk3WHFQZU5P
            cGZoeC9uTlQzUkpCeXlNaHREWFBUQTdSZVhRCkY5aDhUUW45ZUprbE1wNzVvd2wx
            OXlvMEwzakg5QjRBZ2wySUZDMmY3MnMKLS0tIFBqRzZ0ZURCWGZ4elA1T1lDYjNV
            Wk9VdXhNQ3hwbDRZMWVDb0JFTTNPanMKMSyA9JVMIBRn070073qvUIFHdqRnRNrz
            MFWebjlfPfUER7oJnnunWP4xFrrFN2lOZkBaqGmiO1rH4AnjX5AlIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-18T23:33:02Z"
    mac: ENC[AES256_GCM,data:Tv58mvM5dUCxuNsvtqOyDNcWFrK4UYiqDMB21UPDVfx1L/ZWG9mNP5qH3MhAATIMiy9ERtZr8mq3/+jxGSYILQEQ4HF0lx4R0TuWM0r14sjyx3wfMY66rW8Z63N55v4gkjdFbxUyljRKHBTz624IHfliy+pZFfn49K1bTUY4ylk=,iv:RV9sB/NE+x9C3c830odGWDSu+f/rwSsVKy2fmOonuYU=,tag:IgMfSAfrS336TvIzjXokaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
