apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:hLlKpGaSMlPtQ3yv65drpDfW+vvHLcxtC9nvulIGn7iu7pMZ5LgIVg==,iv:w581Qv6VD619sCXXwNdXezlv5DV7u6Ho0I5qQFsqn3o=,tag:HgDKEj3ISSuperIfpJ1Azw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ah9ykhxj8jzudx6mu40wazdv9nd3n5zhd86908k5q6l5g53sg5asvwcms5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNFp1ditZeFVjMWtqNkpO
            dFE3U2g0ajk1SkMybEkrUHp1MUFtUHhGYno0CmIreGZZbk41RUNnQ3p2YnpNVkls
            bVAzc2J6VTkxVStVbTFvR0JDTVNqUXMKLS0tIGhybGxpaWdzNnlFMmVLU3RVT0FB
            R1pxWDJqS2lDek92bFJWaXFwREtWNEkKkQn8lgp71GRgCTlOAcmCs/w3ZA+uwmjj
            BkSQoUB0TnTeC5gNP8bzzsLSlKSlvCAyiY6Dnpajkai4V5512wWlZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T18:09:35Z"
    mac: ENC[AES256_GCM,data:c9U/Qey3UPZXsgTgMc7nqktO+9yJzNawSzF8FnwEX4s0nzeLBTFeLDD4cBseYTuJfFRJAKP+k4mV+8RxzZyaV/74MtkMxybOubbsNo+GBb5rGJYnMORipqCnDr2c4bGx3V3TDQNrb8JQRQUJfD/JP+AtJkj4if8UKOnK2V3C+e4=,iv:63SSCRsd8IB71Xzunugm63kTDWXGCZmhOy20/oBp04I=,tag:3xB6XvITacxszanJmU+T2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
