apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:tZbcwaraynlFRgryyykhHOrlwTNRgsaUIYOaucu+XbMOBil4o31LZg==,iv:KltsWMbi1lkbgvoPpxcgHasZXUUeCfkTgGt3K/s8344=,tag:S1nzSDg1f7jThBRKbqYgLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ah9ykhxj8jzudx6mu40wazdv9nd3n5zhd86908k5q6l5g53sg5asvwcms5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc1lDMllZMC80Nnp3cmVM
            ejFVVkY3aGpMVnIwdk85eGdOaTlNVnZkMEFZCkJ4UGw5b295dm5tMVNZTWovK0Vr
            ZlQxTm96ZzBFTlRaM1ZXeitZR1ovSm8KLS0tIFR6QnZkSHAvSGVnS1hvS3p2NDlZ
            RENYTWk0S1k0Qnc2Z2s0ck1mZEtZL2MKzi0PrisdCU7uSZ0BCzWjh3RnWoZ0I/lb
            4Onm7rrUdYi02AE4xhGYV1Ma5TE2BCYcAHqHdXKwPagmq7GrKugMLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-04T17:05:23Z"
    mac: ENC[AES256_GCM,data:UBIwKDTzq6W4SuC7tI1j9+NO/KfI/OP3bP7JavvDGojN1TZGeFuH4ZM/cw4IsI6BQN+AEpg0ueK0HvfXRJoLS6op6vf0wtLtVjtZ97xh374yGTH5xdpxFCys87cxymBUSZSBX6xemXF5eTRJTx3jwheM5/rG93MCeRsl4FheZFU=,iv:/Q4ntl4ESKoYVS89jc2B+1HaMOemxjOydMrJ9NXT48Y=,tag:OoBd4QvpA5IoO5aZBJOU/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
